# Site settings
title: "Presentations"
description: "A repository of presentation handouts created by Mark Newcomb.  Some handouts may be incomplete without an accompanying presentation.  Nothing on this website is intended to be a substitute for professional medical advice, diagnosis, or treatment."
baseurl: ""
url: "http://mdnukem.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3
theme: jekyll-theme-minimal

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/alixedi
  - title: "git"
    url: http://github.com/alixedi
  - title: "rss"
    url: /feed.xml
